### ISSUE TITLE
[#1][Critical] Lack of code causes game to suffer critical existence failure

### ISSUE THREAD

**Issue by DicePriestess** [Project-Launch-Escape/game-design#1]
CPU: i5-9600k
GPU: RX 6800
64GB RAM

Issue: Due to lack of code, game does not exist.

Steps to reproduce: None required. This is a practice issue.

**Comment by DrPenguin1** [comment]
hate when this happens

**Comment by dagriefaa** [comment]
real

**Comment by warior456** [comment]
I regret to inform you but i believe this is the wrong repository to report it, you should report it to the nonexistent main game repository
